CREATE TABLE IF NOT EXISTS "Matches" (
    "id" INTEGER PRIMARY KEY,
    "date" TEXT,
    "matchday" INTEGER,
    "homeTeam" TEXT,
    "awayTeam" TEXT,
    "homeGoals" INTEGER,
    "awayGoals" INTEGER,
    "totalGoals" INTEGER,
    "redCards" INTEGER,
    "yellowCards" INTEGER,
    "ownGoals" INTEGER,
    "volleyGoals" INTEGER,
    "headerGoals" INTEGER,
    "freeKickGoals" INTEGER,
    "penaltyScored" INTEGER,
    "homeShotsOnGoal" INTEGER,
    "awayShotsOnGoal" INTEGER,
    "extraTime" INTEGER
);