"""update

Revision ID: 5129aae6a0db
Revises: 
Create Date: 2022-01-18 19:29:33.717343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5129aae6a0db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('homeTeam', sa.String(length=255), nullable=False),
    sa.Column('awayTeam', sa.String(length=255), nullable=False),
    sa.Column('extraTime', sa.Integer(), nullable=False),
    sa.Column('totalGoals', sa.Integer(), nullable=False),
    sa.Column('volleyGoals', sa.Integer(), nullable=False),
    sa.Column('headerGoals', sa.Integer(), nullable=False),
    sa.Column('freeKickGoals', sa.Integer(), nullable=False),
    sa.Column('penaltyScored', sa.Integer(), nullable=False),
    sa.Column('yellowCards', sa.Integer(), nullable=False),
    sa.Column('redCards', sa.Integer(), nullable=False),
    sa.Column('ownGoals', sa.Integer(), nullable=False),
    sa.Column('shotsOnTarget', sa.Integer(), nullable=False),
    sa.Column('totalShots', sa.Integer(), nullable=False),
    sa.Column('aidansScore', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Match')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Match',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.TEXT(), nullable=True),
    sa.Column('matchday', sa.INTEGER(), nullable=True),
    sa.Column('homeTeam', sa.TEXT(), nullable=True),
    sa.Column('awayTeam', sa.TEXT(), nullable=True),
    sa.Column('homeGoals', sa.INTEGER(), nullable=True),
    sa.Column('awayGoals', sa.INTEGER(), nullable=True),
    sa.Column('totalGoals', sa.INTEGER(), nullable=True),
    sa.Column('redCards', sa.INTEGER(), nullable=True),
    sa.Column('yellowCards', sa.INTEGER(), nullable=True),
    sa.Column('ownGoals', sa.INTEGER(), nullable=True),
    sa.Column('volleyGoals', sa.INTEGER(), nullable=True),
    sa.Column('headerGoals', sa.INTEGER(), nullable=True),
    sa.Column('freeKickGoals', sa.INTEGER(), nullable=True),
    sa.Column('penaltyScored', sa.INTEGER(), nullable=True),
    sa.Column('homeShotsOnGoal', sa.INTEGER(), nullable=True),
    sa.Column('awayShotsOnGoal', sa.INTEGER(), nullable=True),
    sa.Column('extraTime', sa.INTEGER(), nullable=True),
    sa.Column('aidansScore', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('match')
    # ### end Alembic commands ###
